/** One music term explained for a total beginner; GLOSSARY is ordered so each definition only leans on earlier ones. */
export interface GlossaryEntry {
  id: string;
  term: string;
  /** Lower-case words/phrases that trigger this entry (list plurals and verb forms explicitly). */
  match: string[];
  plain: string;
  why: string;
  /** Where the definition was checked (vault Research/glossary/<id>.md); never shown in the app. */
  sources: string[];
}

// Foundations first: each definition only uses terms above it (enforced by tests/engine/glossary.test.ts).
export const GLOSSARY: GlossaryEntry[] = [
  {
    id: "string_numbers", term: "Strings and string numbers",
    match: ["string", "strings", "string 1", "string 2", "string 3", "string 4", "string 5", "string 6", "low e", "high e"],
    plain: "The guitar has six strings, numbered from the thinnest: string 1 is the thin, highest-sounding high E (nearest the floor as you hold it) and string 6 is the thick, low E. Diagrams draw them as vertical lines with string 6 on the left.",
    why: "Thinner, tighter strings vibrate faster and so sound higher, which is why the numbering runs from thin and high to thick and low.",
    sources: ["vault:Research/glossary/string_numbers.md", "Berklee Online, Guitar Notation Basics — https://online.berklee.edu/takenote/guitar-notation-basics/", "Sound Pure, The Parts of an Acoustic Guitar — https://www.soundpure.com/a/expert-advice/guitars/parts-of-an-acoustic-guitar/"],
  },
  {
    id: "fret", term: "Fret",
    match: ["fret", "frets", "fretted", "fretting"],
    plain: "The thin metal strips across the long arm of the guitar. Pressing a string just behind a fret shortens the part that vibrates, so it sounds higher; \"fret 3\" means the space just behind strip number 3, counting from the top.",
    why: "A shorter string vibrates faster; each fret raises the sound by the same small step, and 12 frets up gives the same sound one level higher.",
    sources: ["vault:Research/glossary/fret.md", "HyperPhysics, Vibrating String — http://hyperphysics.phy-astr.gsu.edu/hbase/Waves/string.html", "Sound Pure, The Parts of an Acoustic Guitar — https://www.soundpure.com/a/expert-advice/guitars/parts-of-an-acoustic-guitar/"],
  },
  {
    id: "fretboard", term: "Fretboard / neck",
    match: ["fretboard", "fretboards", "neck"],
    plain: "The neck is the long wooden arm of the guitar; its playing surface, with the frets set into it, is the fretboard. The dots on it mark frets 3, 5, 7, 9 and 12 to help you find your place.",
    why: "Every sound the guitar can make sits somewhere on this grid of strings and frets, so learning its layout is learning where sounds live.",
    sources: ["vault:Research/glossary/fretboard.md", "Sound Pure, The Parts of an Acoustic Guitar — https://www.soundpure.com/a/expert-advice/guitars/parts-of-an-acoustic-guitar/", "Berklee Online, Guitar Notation Basics — https://online.berklee.edu/takenote/guitar-notation-basics/"],
  },
  {
    id: "nut", term: "Nut",
    match: ["nut"],
    plain: "The small slotted strip at the top of the neck, where it meets the headstock. Strings rest in its slots, and a string played without fretting vibrates from the nut down to where it is anchored on the body; diagrams show it as a thick top line.",
    why: "The nut sets the full length of each string, so it fixes the lowest sound a string can make; every fret counts up from it.",
    sources: ["vault:Research/glossary/nut.md", "Sound Pure, The Parts of an Acoustic Guitar — https://www.soundpure.com/a/expert-advice/guitars/parts-of-an-acoustic-guitar/", "Berklee Online, Guitar Notation Basics — https://online.berklee.edu/takenote/guitar-notation-basics/"],
  },
  {
    id: "bridge", term: "Bridge (two meanings)",
    match: ["bridge", "bridges"],
    plain: "1) On the guitar, the bridge is the part on the body where the strings are anchored. 2) In a song, the bridge is a contrasting section, usually heard once, that takes the music somewhere new before the familiar parts come back.",
    why: "Both meanings are links: one carries the strings' vibration into the body, the other gives the ear a contrast so the return of the familiar sounds fresh.",
    sources: ["vault:Research/glossary/bridge.md", "Sound Pure, The Parts of an Acoustic Guitar — https://www.soundpure.com/a/expert-advice/guitars/parts-of-an-acoustic-guitar/", "Berklee Online, How to Write a Bridge to a Song — https://online.berklee.edu/takenote/writing-bridges-for-your-songs-can-be-much-easier/"],
  },
  {
    id: "chord_diagram", term: "Chord diagram / chord box",
    match: ["chord diagram", "chord diagrams", "chord box", "chord boxes", "card"],
    plain: "A grid picture of the neck as if the guitar stood upright facing you: vertical lines are strings (string 6 on the left), horizontal lines are frets, dots show where fingers go. In this app, \"the card\" is the panel under the practice steps; besides finger diagrams it can show a fretboard map or a picking pattern.",
    why: "It turns where your fingers go into a picture you read at a glance, so you can spend your attention on how it sounds.",
    sources: ["vault:Research/glossary/chord_diagram.md", "Berklee Online, Guitar Notation Basics — https://online.berklee.edu/takenote/guitar-notation-basics/"],
  },
  {
    id: "tab", term: "Tab",
    match: ["tab", "tabs", "tablature"],
    plain: "Guitar writing with six horizontal lines, one per string; the top line is string 1 (high E) and the bottom is string 6. A number on a line tells you which fret to play on that string; 0 means play it without fretting.",
    why: "Tab shows exactly where to play on the fretboard, which makes it the quickest way to read a part on guitar.",
    sources: ["vault:Research/glossary/tab.md", "Berklee Online, Guitar Notation Basics — https://online.berklee.edu/takenote/guitar-notation-basics/"],
  },
  {
    id: "fretting_hand", term: "Fretting hand / picking hand",
    match: ["fretting hand", "fretting-hand", "fretting hands", "picking hand", "pick hand", "picking-hand"],
    plain: "The fretting hand presses strings against the fretboard (the left hand for most right-handed players). The picking hand sounds the strings over the guitar's body, with fingers or a plastic tool.",
    why: "Two jobs, two hands: the fretting hand chooses how high each string sounds, the picking hand decides when and how loudly it sounds.",
    sources: ["vault:Research/glossary/fretting_hand.md", "Berklee Online, Guitar Notation Basics — https://online.berklee.edu/takenote/guitar-notation-basics/"],
  },
  {
    id: "pick", term: "Pick",
    match: ["pick", "picks", "plectrum"],
    plain: "A small, thin piece of plastic held between thumb and first finger of the picking hand and used to strike the strings. Also called a plectrum; to \"pick\" a string is to sound it this way.",
    why: "A pick gives a clear, even attack on each string, which helps you sound strings exactly when you mean to.",
    sources: ["vault:Research/glossary/pick.md", "Berklee Online, Guitar Notation Basics — https://online.berklee.edu/takenote/guitar-notation-basics/"],
  },
  {
    id: "strum", term: "Strum",
    match: ["strum", "strums", "strummed", "strumming"],
    plain: "Brushing the pick or fingers across several strings in one sweeping movement, downwards (towards the floor) or upwards, so the strings sound together.",
    why: "Strumming sounds several strings at once and keeps time, so it is how a guitar fills out a song and drives it forward.",
    sources: ["vault:Research/glossary/strum.md", "Berklee Online, Guitar Notation Basics — https://online.berklee.edu/takenote/guitar-notation-basics/"],
  },
  {
    id: "mute", term: "Mute / muted",
    match: ["mute", "mutes", "muted", "muting"],
    plain: "Stopping strings from ringing by touching them lightly, with either hand, so a strum gives a short thud or \"chk\" instead of a ringing sound. A muted strum still moves in time; it just sounds dull.",
    why: "Silence is part of rhythm: cutting the ring short lets you place sounds and gaps exactly where you want them.",
    sources: ["vault:Research/glossary/mute.md", "JustinGuitar — Muting techniques — https://www.justinguitar.com/"],
  },
  {
    id: "shape", term: "Shape",
    match: ["shape", "shapes"],
    plain: "A fixed pattern of fingers on the fretboard that you can learn once and recognise again. Many shapes can be moved up or down the neck as a block and still work.",
    why: "Because every fret is the same size step, moving a whole shape along the neck keeps the gaps between its sounds the same, just higher or lower.",
    sources: ["vault:Research/glossary/shape.md", "Berklee Online, Guitar Notation Basics — https://online.berklee.edu/takenote/guitar-notation-basics/", "Sound Pure, The Parts of an Acoustic Guitar — https://www.soundpure.com/a/expert-advice/guitars/parts-of-an-acoustic-guitar/"],
  },
  {
    id: "position", term: "Position",
    match: ["position", "positions"],
    plain: "Where your fretting hand sits along the neck, named by the fret your first finger covers. With your first finger at fret 5, the other fingers cover frets 6, 7 and 8, one finger per fret.",
    why: "Staying in one position lets you reach a whole group of sounds without moving your hand, so you can listen rather than hunt.",
    sources: ["vault:Research/glossary/position.md", "Berklee Online, Guitar Notation Basics — https://online.berklee.edu/takenote/guitar-notation-basics/"],
  },
  {
    id: "note", term: "Note",
    match: ["note", "notes"],
    plain: "A single musical sound at one particular height (how high or low it sounds). Notes are named with the letters A to G; each string and fret on the guitar gives you one.",
    why: "A note is one steady vibration; music is built by choosing which of these vibrations to play together or one after another.",
    sources: ["vault:Research/glossary/note.md", "HyperPhysics, Musical Scales and Intervals — http://hyperphysics.phy-astr.gsu.edu/hbase/Music/mussca.html", "Open Music Theory, Half Steps, Whole Steps, and Accidentals — https://viva.pressbooks.pub/openmusictheory/chapter/half-and-whole-steps/"],
  },
  {
    id: "pitch", term: "Pitch",
    match: ["pitch", "pitches"],
    plain: "How high or low a note sounds. It is set by how many times per second the string vibrates (its frequency, in hertz): thinner, tighter or shorter strings vibrate faster and sound higher.",
    why: "Pitch is frequency; when two pitches' frequencies form simple ratios, their vibrations line up and the ear hears them blend.",
    sources: ["vault:Research/glossary/pitch.md", "HyperPhysics, Pitch — http://hyperphysics.phy-astr.gsu.edu/hbase/Sound/pitch.html", "HyperPhysics, Vibrating String — http://hyperphysics.phy-astr.gsu.edu/hbase/Waves/string.html"],
  },
  {
    id: "in_tune", term: "In tune",
    match: ["in tune", "in-tune", "out of tune", "tuning", "tuned"],
    plain: "A note is in tune when its pitch is exactly where it should be, either matching a tuner or matching another note. Out of tune notes sound slightly sour, and you hear a slow wobble between them.",
    why: "Two slightly different frequencies drift in and out of step, causing that wobble; when the pitches match exactly, the wobble stops.",
    sources: ["vault:Research/glossary/in_tune.md", "HyperPhysics, Musical Scales and Intervals — http://hyperphysics.phy-astr.gsu.edu/hbase/Music/mussca.html", "Plomp & Levelt (1965), Tonal Consonance and Critical Bandwidth, JASA 38:548 — https://www.mpi.nl/world/materials/publications/levelt/Plomp_Levelt_Tonal_1965.pdf"],
  },
  {
    id: "unison", term: "Unison",
    match: ["unison", "unisons"],
    plain: "Two notes at exactly the same pitch, played together. On guitar, string 6 at fret 5 and string 5 played without fretting are a unison: both are A.",
    why: "A unison is the simplest ratio of all, 1:1, so the two vibrations match completely and fuse into one sound.",
    sources: ["vault:Research/glossary/unison.md", "HyperPhysics, Musical Scales and Intervals — http://hyperphysics.phy-astr.gsu.edu/hbase/Music/mussca.html", "Open Music Theory, Intervals — https://viva.pressbooks.pub/openmusictheory/chapter/intervals/"],
  },
  {
    id: "octave", term: "Octave",
    match: ["octave", "octaves"],
    plain: "The distance from one note to the next note with the same letter name, higher or lower. On one string it is 12 frets up: string 6 played without fretting is E, and at fret 12 it is E again, higher.",
    why: "The higher note vibrates exactly twice as fast (2:1), so the two blend so closely they sound like the same note, which is why they share a name.",
    sources: ["vault:Research/glossary/octave.md", "HyperPhysics, Musical Scales and Intervals — http://hyperphysics.phy-astr.gsu.edu/hbase/Music/mussca.html", "Open Music Theory, Half Steps, Whole Steps, and Accidentals — https://viva.pressbooks.pub/openmusictheory/chapter/half-and-whole-steps/"],
  },
  {
    id: "consonance", term: "Consonance / dissonance",
    match: ["consonant", "consonance", "dissonant", "dissonance", "clash", "clashes", "clashing"],
    plain: "Consonant notes sound smooth and settled together; dissonant notes clash and sound rough or restless. Both are useful: music moves by building up clashes and then easing them.",
    why: "Every note contains a series of higher overtones (the harmonic series); simple ratios like the octave's 2:1 or 3:2 line those overtones up, while complex ratios make nearby overtones rub.",
    sources: ["vault:Research/glossary/consonance.md", "HyperPhysics, Musical Scales and Intervals — http://hyperphysics.phy-astr.gsu.edu/hbase/Music/mussca.html", "Plomp & Levelt (1965), Tonal Consonance and Critical Bandwidth, JASA 38:548 — https://www.mpi.nl/world/materials/publications/levelt/Plomp_Levelt_Tonal_1965.pdf", "MTSU (W. Roberts), Scientific Theory of Consonance — https://w1.mtsu.edu/faculty/wroberts/teaching/consonance.php"],
  },
  {
    id: "drone", term: "Drone",
    match: ["drone", "drones"],
    plain: "One note held or repeated underneath while you play or sing other notes over it, like the low hum of bagpipes. A string left ringing, such as low E, works as a drone.",
    why: "Against a fixed drone you can hear each new note's consonance or dissonance clearly, which trains your ear to feel the gaps between notes.",
    sources: ["vault:Research/glossary/drone.md", "HyperPhysics, Musical Scales and Intervals — http://hyperphysics.phy-astr.gsu.edu/hbase/Music/mussca.html", "MTSU (W. Roberts), Scientific Theory of Consonance — https://w1.mtsu.edu/faculty/wroberts/teaching/consonance.php"],
  },
  {
    id: "half_step", term: "Half step",
    match: ["half step", "half steps", "half-step", "semitone", "semitones"],
    plain: "The smallest gap between two notes in Western music: one fret on the guitar. Move from fret 3 to fret 4 on any string and you have moved a half step.",
    why: "There are 12 half steps in an octave, all the same size, and every musical gap is counted in them.",
    sources: ["vault:Research/glossary/half_step.md", "Open Music Theory, Half Steps, Whole Steps, and Accidentals — https://viva.pressbooks.pub/openmusictheory/chapter/half-and-whole-steps/", "musictheory.net, Steps and Accidentals — https://www.musictheory.net/lessons/20"],
  },
  {
    id: "whole_step", term: "Whole step",
    match: ["whole step", "whole steps", "whole-step"],
    plain: "Two half steps together: two frets on the guitar, for example fret 3 to fret 5 on the same string.",
    why: "Patterns of whole (W) and half (H) steps build every family of notes you'll learn; the brightest, most common one runs W-W-H-W-W-W-H.",
    sources: ["vault:Research/glossary/whole_step.md", "Open Music Theory, Half Steps, Whole Steps, and Accidentals — https://viva.pressbooks.pub/openmusictheory/chapter/half-and-whole-steps/", "musictheory.net, Steps and Accidentals — https://www.musictheory.net/lessons/20"],
  },
  {
    id: "sharp_flat", term: "Sharp and flat (# and b)",
    match: ["sharps", "flats", "flattens", "flattened", "sharpened", "flat 2nd", "flat 3rd", "flat 5th", "flat 6th", "flat 7th", "sharp 4th", "sharp 5th"],
    plain: "A sharp (#) raises a note by one half step, one fret higher; a flat (b) lowers it by one half step, one fret lower. F# is one fret above F; Bb is one fret below B.",
    why: "There are 12 half steps in an octave but only seven letters, so the five notes in between are named as sharps or flats of their neighbours.",
    sources: ["vault:Research/glossary/sharp_flat.md", "musictheory.net, Steps and Accidentals — https://www.musictheory.net/lessons/20", "Open Music Theory, Half Steps, Whole Steps, and Accidentals — https://viva.pressbooks.pub/openmusictheory/chapter/half-and-whole-steps/"],
  },
  {
    id: "interval", term: "Interval",
    match: ["interval", "intervals"],
    plain: "The distance between two notes, counted in half steps and named by how many letter names it spans: C up to E covers C, D, E, so it is numbered three.",
    why: "Intervals are the building blocks of music; each has a frequency ratio, and that ratio decides how consonant or dissonant the two notes sound.",
    sources: ["vault:Research/glossary/interval.md", "Open Music Theory, Intervals — https://viva.pressbooks.pub/openmusictheory/chapter/intervals/", "HyperPhysics, Musical Scales and Intervals — http://hyperphysics.phy-astr.gsu.edu/hbase/Music/mussca.html"],
  },
  {
    id: "root", term: "Root",
    match: ["root", "roots", "root note", "root notes"],
    plain: "The note a group of notes is built up from and named after. In a G shape, G is the root, and every other note is measured as an interval above it; diagrams often mark it specially.",
    why: "Every interval is counted up from the root, so if you know where the root sits on string 6 or 5, you can move any shape and keep its sound.",
    sources: ["vault:Research/glossary/root.md", "Open Music Theory, Intervals — https://viva.pressbooks.pub/openmusictheory/chapter/intervals/", "Berklee Online, Guitar Notation Basics — https://online.berklee.edu/takenote/guitar-notation-basics/"],
  },
  {
    id: "third", term: "3rd",
    match: ["3rd", "3rds"],
    plain: "The interval spanning three letter names, such as C up to E. It comes in two sizes: three half steps (three frets) or four half steps (four frets).",
    why: "Stacking 3rds on a root is the basic way notes are combined, and which size sits on the root decides whether the result sounds bright or dark.",
    sources: ["vault:Research/glossary/third.md", "Open Music Theory, Intervals — https://viva.pressbooks.pub/openmusictheory/chapter/intervals/", "HyperPhysics, Musical Scales and Intervals — http://hyperphysics.phy-astr.gsu.edu/hbase/Music/mussca.html"],
  },
  {
    id: "major_third", term: "Major 3rd",
    match: ["major 3rd", "major 3rds", "major third", "major thirds"],
    plain: "The larger 3rd: four half steps, four frets up the same string. C to E and G to B are major 3rds.",
    why: "Its frequency ratio is close to 5:4, a low overtone in the harmonic series, which gives a bright, happy sound when it sits on the root.",
    sources: ["vault:Research/glossary/major_third.md", "HyperPhysics, Musical Scales and Intervals — http://hyperphysics.phy-astr.gsu.edu/hbase/Music/mussca.html", "Open Music Theory, Intervals — https://viva.pressbooks.pub/openmusictheory/chapter/intervals/"],
  },
  {
    id: "minor_third", term: "Minor 3rd",
    match: ["minor 3rd", "minor 3rds", "minor third", "minor thirds"],
    plain: "The smaller 3rd: three half steps, three frets up the same string. A to C and E to G are minor 3rds; it is one fret narrower than a major 3rd.",
    why: "Its ratio is close to 6:5; lowering a major 3rd by one half step to a minor 3rd turns a bright, happy sound dark and sad.",
    sources: ["vault:Research/glossary/minor_third.md", "HyperPhysics, Musical Scales and Intervals — http://hyperphysics.phy-astr.gsu.edu/hbase/Music/mussca.html", "Open Music Theory, Intervals — https://viva.pressbooks.pub/openmusictheory/chapter/intervals/"],
  },
  {
    id: "fifth", term: "5th",
    match: ["5th", "5ths", "fifth", "fifths"],
    plain: "The interval spanning five letter names, normally seven half steps: G to D. On guitar, fret 3 on string 6 and fret 5 on string 5 make a 5th (G and D).",
    why: "Its 3:2 ratio is the most consonant after the octave, so the 5th gives the root solid, stable support.",
    sources: ["vault:Research/glossary/fifth.md", "HyperPhysics, Musical Scales and Intervals — http://hyperphysics.phy-astr.gsu.edu/hbase/Music/mussca.html", "Open Music Theory, Intervals — https://viva.pressbooks.pub/openmusictheory/chapter/intervals/", "MTSU (W. Roberts), Scientific Theory of Consonance — https://w1.mtsu.edu/faculty/wroberts/teaching/consonance.php"],
  },
  {
    id: "fourth", term: "4th",
    match: ["4th", "4ths", "fourth", "fourths"],
    plain: "The interval spanning four letter names, normally five half steps (five frets): G up to C. Most neighbouring guitar strings are a 4th apart.",
    why: "Its 4:3 ratio is the most consonant interval after the octave and the 5th, so strings tuned in 4ths ring together cleanly and keep finger shapes within one hand's reach.",
    sources: ["vault:Research/glossary/fourth.md", "Open Music Theory — Intervals — https://viva.pressbooks.pub/openmusictheory/chapter/intervals/"],
  },
  {
    id: "sixth", term: "6th",
    match: ["6th", "6ths", "sixth", "sixths"],
    plain: "The interval spanning six letter names: eight or nine half steps, as in C up to A (nine). Turn a 3rd upside down, moving its lower note up an octave, and you get a 6th.",
    why: "A 6th is a 3rd flipped by an octave, so it keeps a 3rd's sweet, consonant blend while spreading the notes wider apart.",
    sources: ["vault:Research/glossary/sixth.md", "Open Music Theory, Intervals — https://viva.pressbooks.pub/openmusictheory/chapter/intervals/", "HyperPhysics, Musical Scales and Intervals — http://hyperphysics.phy-astr.gsu.edu/hbase/Music/mussca.html"],
  },
  {
    id: "seventh", term: "7th",
    match: ["7th", "7ths", "seventh", "sevenths", "b7"],
    plain: "The interval spanning seven letter names: ten or eleven half steps, just one or two frets short of the octave. C up to B is eleven; C up to Bb is ten.",
    why: "Its frequency ratio is complex (about 15:8 or 16:9), so it sounds restless and seems to lean towards the octave just above.",
    sources: ["vault:Research/glossary/seventh.md", "Open Music Theory, Intervals — https://viva.pressbooks.pub/openmusictheory/chapter/intervals/", "HyperPhysics, Musical Scales and Intervals — http://hyperphysics.phy-astr.gsu.edu/hbase/Music/mussca.html"],
  },
  {
    id: "ninth", term: "9th",
    match: ["9th", "9ths", "ninth", "ninths"],
    plain: "Counting past the octave: counting the root as 1, the octave is number 8, so the 9th is the 2nd an octave up, 14 half steps above the root. From C, the 9th is the D above the higher C.",
    why: "Numbers above 8 mean \"this note, placed an octave higher\"; spreading a close 2nd out by an octave softens its clash into colour.",
    sources: ["vault:Research/glossary/ninth.md", "teoria.com, Compound and simple intervals — https://www.teoria.com/en/reference/c/comp-simp.php", "Open Music Theory, Intervals — https://viva.pressbooks.pub/openmusictheory/chapter/intervals/"],
  },
  {
    id: "eleventh", term: "11th",
    match: ["11th", "11ths", "eleventh", "elevenths"],
    plain: "The 4th an octave up: 17 half steps above the root. From C, count C D E F G A B C, then D (9), E (10), F (11): the 11th is the F above the higher C.",
    why: "Subtract 7 from any number past the octave to find its smaller twin: 11 minus 7 is 4, so the 11th sounds like a 4th, spread wider.",
    sources: ["vault:Research/glossary/eleventh.md", "teoria.com, Compound and simple intervals — https://www.teoria.com/en/reference/c/comp-simp.php", "Open Music Theory, Intervals — https://viva.pressbooks.pub/openmusictheory/chapter/intervals/"],
  },
  {
    id: "thirteenth", term: "13th",
    match: ["13th", "13ths", "thirteenth", "thirteenths"],
    plain: "The 6th an octave up: 21 half steps above the root. From C, the 13th is the A above the higher C.",
    why: "Thirteen minus seven is six, so the 13th sounds like a 6th placed high; past 13 the count wraps back onto the root's octaves.",
    sources: ["vault:Research/glossary/thirteenth.md", "teoria.com, Compound and simple intervals — https://www.teoria.com/en/reference/c/comp-simp.php", "Open Music Theory, Intervals — https://viva.pressbooks.pub/openmusictheory/chapter/intervals/"],
  },
  {
    id: "scale", term: "Scale",
    match: ["scale", "scales"],
    plain: "A scale is a set of notes climbing in order from a starting note up to its octave, following a fixed pattern of half steps and whole steps. On guitar you can play one up a single string or across several strings in one position.",
    why: "The pattern of steps gives each scale its sound; the most common runs W-W-H-W-W-W-H, and where the two half steps fall decides its mood.",
    sources: ["vault:Research/glossary/scale.md", "musictheory.net, The Major Scale — https://www.musictheory.net/lessons/21", "Open Music Theory, Introduction to Diatonic Modes and the Chromatic Scale — https://viva.pressbooks.pub/openmusictheory/chapter/intro-to-diatonic-modes-and-the-chromatic-scale/"],
  },
  {
    id: "key", term: "Key",
    match: ["key", "keys"],
    plain: "A key is the set of notes a song mostly uses, taken from one scale, with one note that feels like home. A song 'in G' uses the scale that starts and ends on G, so most of its notes come from it.",
    why: "Staying inside one scale's notes keeps things consonant and settled; notes from outside the key stand out because they break that pattern of steps.",
    sources: ["vault:Research/glossary/key.md", "musictheory.net, Key Signatures — https://www.musictheory.net/lessons/24", "Wikipedia, Key (music) — https://en.wikipedia.org/wiki/Key_(music)"],
  },
  {
    id: "tonic", term: "Home note (tonic)",
    match: ["home note", "home notes", "tonic"],
    plain: "The home note (tonic) is the note a key or scale is named after and built from, the one that sounds finished when you stop on it. In G, it's G: string 6, fret 3.",
    why: "Every other note is heard as a distance (an interval) from the home note, so landing on it makes the ear feel the music has arrived.",
    sources: ["vault:Research/glossary/tonic.md", "musictheory.net, Scale Degrees — https://www.musictheory.net/lessons/23"],
  },
  {
    id: "degree", term: "Scale degree",
    match: ["degree", "degrees", "scale degree", "scale degrees"],
    plain: "A scale degree is a note's number in its scale, counting up from the home note as 1. In a G scale, G is 1, A is 2, B is 3, up to 7, then G returns an octave higher as 1 again.",
    why: "Numbers work in every key, and they name intervals: the 3rd degree sits a 3rd above the home note, the 5th a 5th above.",
    sources: ["vault:Research/glossary/degree.md", "musictheory.net, Scale Degrees — https://www.musictheory.net/lessons/23"],
  },
  {
    id: "major", term: "Major",
    match: ["major"],
    plain: "Major describes a scale, key or sound built on the step pattern W-W-H-W-W-W-H, with a major 3rd (four half steps) above the home note. It's the bright, happy-sounding one: think 'Do-Re-Mi'.",
    why: "A major 3rd matches a strong overtone that every plucked string already contains (the 5th harmonic), which helps major sound bright and stable.",
    sources: ["vault:Research/glossary/major.md", "musictheory.net, The Major Scale — https://www.musictheory.net/lessons/21", "HyperPhysics, Harmonics — http://hyperphysics.phy-astr.gsu.edu/hbase/Music/harmon.html"],
  },
  {
    id: "minor", term: "Minor",
    match: ["minor"],
    plain: "Minor describes a scale, key or sound with a minor 3rd above the home note: three half steps instead of four. It sounds darker or sadder than major, and that one note, the 3rd, makes the difference.",
    why: "Moving a single note down one half step changes the whole mood, which shows how much the 3rd above the home note shapes what we hear.",
    sources: ["vault:Research/glossary/minor.md", "musictheory.net, The Minor Scales — https://www.musictheory.net/lessons/22", "Open Music Theory, Introduction to Diatonic Modes and the Chromatic Scale — https://viva.pressbooks.pub/openmusictheory/chapter/intro-to-diatonic-modes-and-the-chromatic-scale/"],
  },
  {
    id: "natural_minor", term: "Natural minor",
    match: ["natural minor"],
    plain: "Natural minor is the scale with the step pattern W-H-W-W-H-W-W. Compared with major from the same note it has a flat 3rd, flat 6th and flat 7th. E natural minor uses the same notes as G major.",
    why: "It's the same seven notes as a major scale started from a different home note, so the half steps land in new places and bright turns dark.",
    sources: ["vault:Research/glossary/natural_minor.md", "musictheory.net, The Minor Scales — https://www.musictheory.net/lessons/22"],
  },
  {
    id: "relative", term: "Relative major / minor",
    match: ["relative minor", "relative major", "relative minors", "relative majors"],
    plain: "A relative major and minor share exactly the same notes but have different home notes. The relative minor starts on the 6th degree of the major scale: G major and E minor are relatives, both with one sharp (F#).",
    why: "Because the notes match, only the home note changes the mood, so the same fretboard patterns serve both keys.",
    sources: ["vault:Research/glossary/relative.md", "musictheory.net, The Minor Scales — https://www.musictheory.net/lessons/22", "Wikipedia, Relative key — https://en.wikipedia.org/wiki/Relative_key"],
  },
  {
    id: "diatonic", term: "Diatonic",
    match: ["diatonic"],
    plain: "Diatonic means belonging to the key: using only the seven notes of its scale, with no extra sharps or flats. In G, playing only G, A, B, C, D, E and F# is diatonic; adding a Bb is not.",
    why: "Diatonic notes all follow the key's step pattern, so they sit comfortably together; anything from outside stands out as colour.",
    sources: ["vault:Research/glossary/diatonic.md", "Wikipedia, Diatonic and chromatic — https://en.wikipedia.org/wiki/Diatonic_and_chromatic", "Open Music Theory, Collections — https://viva.pressbooks.pub/openmusictheory/chapter/collections/"],
  },
  {
    id: "circle_of_fifths", term: "Circle of fifths",
    match: ["circle of fifths"],
    plain: "The circle of fifths arranges all 12 keys like a clock, each a 5th above the last: C, G, D, A, E and so on. Each step clockwise adds one sharp; each step anticlockwise adds one flat.",
    why: "Neighbouring keys share six of their seven notes, so the circle shows which keys sound closest; the 5th is the most consonant interval after the octave.",
    sources: ["vault:Research/glossary/circle_of_fifths.md", "musictheory.net, Key Signatures — https://www.musictheory.net/lessons/24", "Wikipedia, Circle of fifths — https://en.wikipedia.org/wiki/Circle_of_fifths"],
  },
  {
    id: "chromatic", term: "Chromatic",
    match: ["chromatic"],
    plain: "The chromatic scale is all 12 notes in a row, each a half step from the next: on one string, that's every fret in turn. 'Chromatic' notes are ones from outside the key.",
    why: "Twelve half steps make an octave; every other scale is a selection from these 12, chosen by its pattern of steps.",
    sources: ["vault:Research/glossary/chromatic.md", "Open Music Theory, Introduction to Diatonic Modes and the Chromatic Scale — https://viva.pressbooks.pub/openmusictheory/chapter/intro-to-diatonic-modes-and-the-chromatic-scale/", "Wikipedia, Chromatic scale — https://en.wikipedia.org/wiki/Chromatic_scale"],
  },
  {
    id: "pentatonic", term: "Pentatonic",
    match: ["pentatonic", "pentatonics"],
    plain: "Pentatonic means a scale with five notes per octave ('penta' is Greek for five). The two common ones, major and minor, use the same five notes from different home notes: the G major and E minor versions share the same five notes.",
    why: "Five-note scales skip the two half steps of the seven-note scale, so no two notes are a half step apart; that makes clashes rare, which is why they turn up worldwide.",
    sources: ["vault:Research/glossary/pentatonic.md", "Wikipedia, Pentatonic scale — https://en.wikipedia.org/wiki/Pentatonic_scale", "Open Music Theory, Introduction to Diatonic Modes and the Chromatic Scale — https://viva.pressbooks.pub/openmusictheory/chapter/intro-to-diatonic-modes-and-the-chromatic-scale/"],
  },
  {
    id: "major_pentatonic", term: "Major pentatonic",
    match: ["major pentatonic"],
    plain: "A five-note scale made from the major scale by leaving out its 4th and 7th degrees: 1, 2, 3, 5, 6. In G that's G, A, B, D, E. Bright and open, heard in country, rock and pop.",
    why: "Removing the 4th and 7th removes both half steps, so no two notes clash and almost any note sounds good in the key.",
    sources: ["vault:Research/glossary/major_pentatonic.md", "Wikipedia, Pentatonic scale — https://en.wikipedia.org/wiki/Pentatonic_scale", "Open Music Theory, Introduction to Diatonic Modes and the Chromatic Scale — https://viva.pressbooks.pub/openmusictheory/chapter/intro-to-diatonic-modes-and-the-chromatic-scale/"],
  },
  {
    id: "minor_pentatonic", term: "Minor pentatonic",
    match: ["minor pentatonic"],
    plain: "A five-note scale made from natural minor by leaving out its 2nd and 6th: 1, b3, 4, 5, b7. In E that's E, G, A, B, D, the box pattern most rock guitar solos start from.",
    why: "With no half steps between its notes it can't clash, and it keeps the minor 3rd and flat 7th that give rock its gritty sound.",
    sources: ["vault:Research/glossary/minor_pentatonic.md", "Wikipedia, Pentatonic scale — https://en.wikipedia.org/wiki/Pentatonic_scale", "Open Music Theory, Introduction to Diatonic Modes and the Chromatic Scale — https://viva.pressbooks.pub/openmusictheory/chapter/intro-to-diatonic-modes-and-the-chromatic-scale/"],
  },
  {
    id: "blues_scale", term: "Blues scale",
    match: ["blues scale", "blues scales", "blues", "minor blues", "major blues"],
    plain: "The blues scale (often just 'blues') is the minor pentatonic plus one extra note, the flat 5th: 1, b3, 4, b5, 5, b7. In E: E, G, A, Bb, B, D. Major blues instead adds a flat 3rd to the major pentatonic.",
    why: "The flat 5th squeezes in a half step between the 4th and 5th, a deliberate clash that sounds gritty and pulls towards its neighbours.",
    sources: ["vault:Research/glossary/blues_scale.md", "Wikipedia, Blues scale — https://en.wikipedia.org/wiki/Blues_scale", "Open Music Theory, Chord-Scale Theory — https://viva.pressbooks.pub/openmusictheory/chapter/chord-scale-theory/"],
  },
  {
    id: "blue_note", term: "Blue note",
    match: ["blue note", "blue notes"],
    plain: "A blue note is a bent or slightly flattened version of a note, played for expression: usually somewhere around the flat 3rd, flat 5th or flat 7th. On guitar you often bend the minor 3rd a little towards the major 3rd.",
    why: "Blue notes sit between the 12 notes of the usual Western system, so the ear hears them as expressive, bittersweet clashes rather than mistakes.",
    sources: ["vault:Research/glossary/blue_note.md", "Open Music Theory, Chord-Scale Theory — https://viva.pressbooks.pub/openmusictheory/chapter/chord-scale-theory/", "Wikipedia, Blue note — https://en.wikipedia.org/wiki/Blue_note"],
  },
  {
    id: "mode", term: "Mode",
    match: ["mode", "modes", "modal"],
    plain: "A mode is a scale you get by playing the same seven notes from a different home note. Seven starting points give seven modes. Guitarists mostly learn each as its own step formula from one root, and compare it to major or minor.",
    why: "Moving the home note moves where the two half steps fall, which changes the intervals above the root and so the mood.",
    sources: ["vault:Research/glossary/mode.md", "Open Music Theory, Introduction to Diatonic Modes and the Chromatic Scale — https://viva.pressbooks.pub/openmusictheory/chapter/intro-to-diatonic-modes-and-the-chromatic-scale/", "Open Music Theory, Diatonic Modes — https://viva.pressbooks.pub/openmusictheory/chapter/diatonic-modes/"],
  },
  {
    id: "ionian", term: "Ionian",
    match: ["ionian"],
    plain: "Ionian is the mode built from the 1st degree of the major scale, so it simply is the major scale: W-W-H-W-W-W-H. Bright and happy; heard in most pop, folk and children's songs.",
    why: "It's the reference point: the other modes are described as Ionian or natural minor with one or two notes moved a half step.",
    sources: ["vault:Research/glossary/ionian.md", "Open Music Theory, Introduction to Diatonic Modes and the Chromatic Scale — https://viva.pressbooks.pub/openmusictheory/chapter/intro-to-diatonic-modes-and-the-chromatic-scale/", "Open Music Theory, Diatonic Modes — https://viva.pressbooks.pub/openmusictheory/chapter/diatonic-modes/"],
  },
  {
    id: "dorian", term: "Dorian",
    match: ["dorian"],
    plain: "Dorian is natural minor with a raised 6th: W-H-W-W-W-H-W. It's also the major scale's notes started from the 2nd degree. Minor but cooler and brighter; heard in funk, soul, jazz and Santana-style rock.",
    why: "Raising the 6th a half step lifts the darkest note of natural minor, giving a minor sound with a hopeful edge.",
    sources: ["vault:Research/glossary/dorian.md", "Open Music Theory, Diatonic Modes — https://viva.pressbooks.pub/openmusictheory/chapter/diatonic-modes/", "Wikipedia, Dorian mode — https://en.wikipedia.org/wiki/Dorian_mode"],
  },
  {
    id: "phrygian", term: "Phrygian",
    match: ["phrygian"],
    plain: "Phrygian is natural minor with a flat 2nd: H-W-W-W-H-W-W. It's also the major scale's notes started from the 3rd degree. Dark and Spanish-sounding; heard in flamenco and heavy metal riffs.",
    why: "The flat 2nd sits just a half step above the root, a tight, clashing step that gives it a dark, exotic edge.",
    sources: ["vault:Research/glossary/phrygian.md", "Open Music Theory, Diatonic Modes — https://viva.pressbooks.pub/openmusictheory/chapter/diatonic-modes/", "Wikipedia, Phrygian mode — https://en.wikipedia.org/wiki/Phrygian_mode"],
  },
  {
    id: "lydian", term: "Lydian",
    match: ["lydian"],
    plain: "Lydian is major with a raised (sharp) 4th: W-W-W-H-W-W-H. It's also the major scale's notes started from the 4th degree. Dreamy and floating; heard in film and TV music and Joe Satriani-style rock.",
    why: "The sharp 4th removes the half step between the 3rd and 4th, so nothing tugs downwards and the sound seems to hover.",
    sources: ["vault:Research/glossary/lydian.md", "Open Music Theory, Diatonic Modes — https://viva.pressbooks.pub/openmusictheory/chapter/diatonic-modes/", "Wikipedia, Lydian mode — https://en.wikipedia.org/wiki/Lydian_mode"],
  },
  {
    id: "mixolydian", term: "Mixolydian",
    match: ["mixolydian"],
    plain: "Mixolydian is major with a flat 7th: W-W-H-W-W-H-W. It's also the major scale's notes started from the 5th degree. Bright but relaxed and bluesy; heard in classic rock, blues, folk and Celtic music.",
    why: "Flattening the 7th removes the half step below the root, so there's less pull back home, giving a laid-back, rootsy sound.",
    sources: ["vault:Research/glossary/mixolydian.md", "Open Music Theory, Diatonic Modes — https://viva.pressbooks.pub/openmusictheory/chapter/diatonic-modes/", "Open Music Theory, Chord-Scale Theory — https://viva.pressbooks.pub/openmusictheory/chapter/chord-scale-theory/"],
  },
  {
    id: "aeolian", term: "Aeolian",
    match: ["aeolian"],
    plain: "Aeolian is the mode name for natural minor: W-H-W-W-H-W-W. It's also the major scale's notes started from the 6th degree. Sad or serious; heard in rock ballads, pop and metal.",
    why: "Against major, three notes drop a half step (the 3rd, 6th and 7th), which is why it sounds darker than the bright modes.",
    sources: ["vault:Research/glossary/aeolian.md", "Open Music Theory, Diatonic Modes — https://viva.pressbooks.pub/openmusictheory/chapter/diatonic-modes/", "musictheory.net, The Minor Scales — https://www.musictheory.net/lessons/22"],
  },
  {
    id: "locrian", term: "Locrian",
    match: ["locrian"],
    plain: "Locrian is natural minor with a flat 2nd and a flat 5th: H-W-W-H-W-W-W. It's also the major scale's notes started from the 7th degree. Unstable and rarely used as home; heard mostly in metal.",
    why: "Its 5th is flattened, so the strongest consonance above the root is missing and the home note never feels settled.",
    sources: ["vault:Research/glossary/locrian.md", "Open Music Theory, Introduction to Diatonic Modes and the Chromatic Scale — https://viva.pressbooks.pub/openmusictheory/chapter/intro-to-diatonic-modes-and-the-chromatic-scale/", "Wikipedia, Locrian mode — https://en.wikipedia.org/wiki/Locrian_mode"],
  },
  {
    id: "harmonic_minor", term: "Harmonic minor",
    match: ["harmonic minor"],
    plain: "Harmonic minor is natural minor with its 7th raised a half step, leaving a wide gap of three half steps between the 6th and 7th. Heard in classical music, neoclassical metal, and Middle Eastern and Eastern European folk.",
    why: "The raised 7th sits a half step below the root, pulling strongly home, while the three-half-step gap gives its exotic flavour.",
    sources: ["vault:Research/glossary/harmonic_minor.md", "musictheory.net, The Minor Scales — https://www.musictheory.net/lessons/22", "Wikipedia, Minor scale — https://en.wikipedia.org/wiki/Minor_scale"],
  },
  {
    id: "melodic_minor", term: "Melodic minor",
    match: ["melodic minor"],
    plain: "Melodic minor is natural minor with both the 6th and 7th raised a half step: W-H-W-W-W-W-H, which is major with a flat 3rd. Classical music uses it going up only; jazz uses it both ways.",
    why: "Raising the 6th as well smooths out the wide gap of harmonic minor while keeping the half step that pulls up to the root.",
    sources: ["vault:Research/glossary/melodic_minor.md", "musictheory.net, The Minor Scales — https://www.musictheory.net/lessons/22", "Open Music Theory, Chord-Scale Theory — https://viva.pressbooks.pub/openmusictheory/chapter/chord-scale-theory/"],
  },
  {
    id: "phrygian_dominant", term: "Phrygian dominant",
    match: ["phrygian dominant"],
    plain: "This scale is Phrygian with a major 3rd instead of a minor 3rd: 1, b2, 3, 4, 5, b6, b7. It's harmonic minor started from its 5th degree. It's the sound of flamenco, Middle Eastern music and much heavy metal.",
    why: "The half step from the flat 2nd down to the root, plus the three-half-step gap up to the 3rd, gives its unmistakable exotic sound.",
    sources: ["vault:Research/glossary/phrygian_dominant.md", "Wikipedia, Phrygian dominant scale — https://en.wikipedia.org/wiki/Phrygian_dominant_scale", "Open Music Theory, Chord-Scale Theory — https://viva.pressbooks.pub/openmusictheory/chapter/chord-scale-theory/"],
  },
  {
    id: "lydian_dominant", term: "Lydian dominant",
    match: ["lydian dominant"],
    plain: "This scale is Mixolydian with a sharp 4th, or Lydian with a flat 7th: 1, 2, 3, #4, 5, 6, b7. It's melodic minor started from its 4th degree. Used in jazz and fusion.",
    why: "The sharp 4th adds Lydian's floating brightness to Mixolydian's relaxed flat 7th, a blend jazz players reach for as extra colour.",
    sources: ["vault:Research/glossary/lydian_dominant.md", "Wikipedia, Acoustic scale — https://en.wikipedia.org/wiki/Acoustic_scale", "Open Music Theory, Chord-Scale Theory — https://viva.pressbooks.pub/openmusictheory/chapter/chord-scale-theory/"],
  },
  {
    id: "altered", term: "Altered scale",
    match: ["altered", "altered scale"],
    plain: "The altered scale is melodic minor started from its 7th degree: 1, b2, #2, 3, b5, #5, b7. Every note except the root, 3rd and flat 7th is moved a half step. Jazz players use it just before landing home.",
    why: "Packing in clashing notes builds a strain the ear wants released, so arriving at the home sound feels stronger.",
    sources: ["vault:Research/glossary/altered.md", "Wikipedia, Altered scale — https://en.wikipedia.org/wiki/Altered_scale", "Open Music Theory, Chord-Scale Theory — https://viva.pressbooks.pub/openmusictheory/chapter/chord-scale-theory/"],
  },
  {
    id: "bebop", term: "Bebop scale",
    match: ["bebop", "bebop scale", "bebop scales"],
    plain: "A bebop scale is a seven-note scale with one extra in-between note added, making eight. The most common is Mixolydian plus the natural 7th. Jazz players use it in long runs of quick notes.",
    why: "Eight notes fit evenly into a count of four, so the extra note keeps the strongest notes of the scale falling on the strong counts.",
    sources: ["vault:Research/glossary/bebop.md", "Wikipedia, Bebop scale — https://en.wikipedia.org/wiki/Bebop_scale", "Open Music Theory, Chord-Scale Theory — https://viva.pressbooks.pub/openmusictheory/chapter/chord-scale-theory/"],
  },
  {
    id: "diminished_scale", term: "Diminished scale",
    match: ["diminished scale", "diminished scales"],
    plain: "This eight-note scale alternates half and whole steps (H-W-H-W-H-W-H-W, or starting with a whole step). Its pattern repeats every three frets, so one fingering moves up the neck. Used in jazz and metal for an eerie sound.",
    why: "Its strict half-whole symmetry gives it no single home note, so it sounds restless and unsettled.",
    sources: ["vault:Research/glossary/diminished_scale.md", "Wikipedia, Octatonic scale — https://en.wikipedia.org/wiki/Octatonic_scale", "Open Music Theory, Collections — https://viva.pressbooks.pub/openmusictheory/chapter/collections/"],
  },
  {
    id: "chord", term: "Chord",
    match: ["chord", "chords"],
    plain: "Three or more notes sounding together, usually strummed across several strings at once. A chord takes its letter name from its root, the note it is built on.",
    why: "Notes whose pitches line up in simple ratios blend smoothly, so stacking them in 3rds gives a settled, consonant sound.",
    sources: ["vault:Research/glossary/chord.md", "musictheory.net, \"Introduction to Chords\" — https://www.musictheory.net/lessons/40", "Open Music Theory, \"Triads\" — https://viva.pressbooks.pub/openmusictheory/chapter/triads/"],
  },
  {
    id: "triad", term: "Triad",
    match: ["triad", "triads"],
    plain: "The simplest chord: three notes stacked in 3rds, the root, the 3rd and the 5th above it. Most open shapes on the guitar are triads with some of those notes doubled on extra strings.",
    why: "The 3rd decides the mood: four frets above the root sounds major, three frets sounds minor, so moving that one note down a fret turns major into minor.",
    sources: ["vault:Research/glossary/triad.md", "Open Music Theory, \"Triads\" — https://viva.pressbooks.pub/openmusictheory/chapter/triads/", "musictheory.net, \"Introduction to Chords\" — https://www.musictheory.net/lessons/40"],
  },
  {
    id: "diminished", term: "Diminished",
    match: ["diminished"],
    plain: "A triad with a minor 3rd and a 5th lowered by one fret (a flat 5th). It sounds tense and unsettled, and it is written with \"dim\" or a small circle, as in Bdim or B°.",
    why: "Two minor 3rds stacked make a 5th that is a half step short, a clashing interval the ear wants to move away from.",
    sources: ["vault:Research/glossary/diminished.md", "Open Music Theory, \"Triads\" — https://viva.pressbooks.pub/openmusictheory/chapter/triads/", "musictheory.net, \"Introduction to Chords\" — https://www.musictheory.net/lessons/40"],
  },
  {
    id: "augmented", term: "Augmented",
    match: ["augmented"],
    plain: "A triad with a major 3rd and a 5th raised by one fret (a sharp 5th). It sounds dreamy and unstable, and it is written with \"aug\" or a plus sign, as in Caug or C+.",
    why: "Two major 3rds stacked push the 5th a half step too wide; it still has a major 3rd, but that stretched 5th makes it sound unstable, as if waiting to move on.",
    sources: ["vault:Research/glossary/augmented.md", "Open Music Theory, \"Triads\" — https://viva.pressbooks.pub/openmusictheory/chapter/triads/", "musictheory.net, \"Introduction to Chords\" — https://www.musictheory.net/lessons/40"],
  },
  {
    id: "inversion", term: "Inversion",
    match: ["inversion", "inversions", "inverted", "root position", "first inversion", "second inversion"],
    plain: "Which note of a chord is lowest. Root position has the root lowest; first inversion puts the 3rd lowest; second inversion puts the 5th lowest. The chord keeps its name either way.",
    why: "The same notes make the same chord in any order because 3rds and 5ths keep their identity across octaves; only the lowest note changes how grounded it sounds.",
    sources: ["vault:Research/glossary/inversion.md", "Open Music Theory, \"Inversion\" — https://viva.pressbooks.pub/openmusictheory/chapter/inversion/", "musictheory.net, \"Triad Inversion\" — https://www.musictheory.net/lessons/42"],
  },
  {
    id: "chord_tone", term: "Chord tone",
    match: ["chord tone", "chord tones"],
    plain: "Any note that belongs to the chord being played: for a triad, its root, 3rd or 5th. Over a G chord those are G, B and D, wherever they sit on the fretboard.",
    why: "Chord tones sound consonant against the chord because they are part of it, so landing a picked note on one sounds settled rather than clashing.",
    sources: ["vault:Research/glossary/chord_tone.md", "Open Music Theory, \"Embellishing Tones\" — https://viva.pressbooks.pub/openmusictheory/chapter/embellishing-tones/", "Open Music Theory, \"Chord-Scale Theory\" — https://viva.pressbooks.pub/openmusictheory/chapter/chord-scale-theory/"],
  },
  {
    id: "seventh_chord", term: "Seventh chord",
    match: ["seventh chord", "seventh chords", "seventh-chord"],
    plain: "A triad with one more note stacked a 3rd higher: the 7th above the root. That makes four notes, written with a 7, as in G7, Gmaj7 or Gm7.",
    why: "The 7th sits a half step or whole step below the root an octave up, adding a mild clash that makes the chord sound richer and keen to move.",
    sources: ["vault:Research/glossary/seventh_chord.md", "Open Music Theory, \"Seventh Chords\" — https://viva.pressbooks.pub/openmusictheory/chapter/seventh-chords/", "musictheory.net, \"Seventh Chords\" — https://www.musictheory.net/lessons/45", "Open Music Theory, \"Chord Symbols\" — https://viva.pressbooks.pub/openmusictheory/chapter/chord-symbols/"],
  },
  {
    id: "shell", term: "Shell voicing",
    match: ["shell", "shells", "shell voicing", "shell voicings"],
    plain: "A stripped-down seventh chord using only the root, 3rd and 7th, with the 5th left out. On guitar it takes three strings, with the root on string 6 or string 5.",
    why: "The 3rd says major or minor and the 7th says which kind of seventh chord it is; the 5th adds little, so dropping it keeps the sound clear.",
    sources: ["vault:Research/glossary/shell.md", "Open Music Theory, \"Jazz Voicings\" — https://viva.pressbooks.pub/openmusictheory/chapter/jazz-voicings/", "Open Music Theory, \"Seventh Chords\" — https://viva.pressbooks.pub/openmusictheory/chapter/seventh-chords/"],
  },
  {
    id: "voicing", term: "Voicing",
    match: ["voicing", "voicings"],
    plain: "How the notes of a chord are arranged: which strings, which octave, and which note sits on top or lowest. One chord can have many voicings up and down the neck.",
    why: "A chord is named by its notes, not their order, but spacing changes the sound: wide gaps ring open and clear, close notes sound denser.",
    sources: ["vault:Research/glossary/voicing.md", "Open Music Theory, \"Jazz Voicings\" — https://viva.pressbooks.pub/openmusictheory/chapter/jazz-voicings/", "Open Music Theory, \"Triads\" — https://viva.pressbooks.pub/openmusictheory/chapter/triads/"],
  },
  {
    id: "sus", term: "Sus chord",
    match: ["sus", "sus2", "sus4", "suspended", "sus chord", "sus chords"],
    plain: "Short for suspended: a chord with no 3rd, swapped for the 2nd (sus2) or the 4th (sus4). On open D, lift the finger off string 1 for Dsus2, or move it to fret 3 for Dsus4.",
    why: "Without the 3rd the chord is neither major nor minor, so it sounds open and waiting, and the ear wants the 3rd back.",
    sources: ["vault:Research/glossary/sus.md", "Open Music Theory, \"Chord Symbols\" — https://viva.pressbooks.pub/openmusictheory/chapter/chord-symbols/", "Open Music Theory, \"Triads\" — https://viva.pressbooks.pub/openmusictheory/chapter/triads/"],
  },
  {
    id: "add", term: "Add chord",
    match: ["add9", "add11", "add chord", "add chords"],
    plain: "A triad with one extra note and the 3rd kept. Add9 adds the 9th (the 2nd, an octave up); add11 adds the 11th. For Cadd9, play C and move the finger on string 2 to fret 3.",
    why: "Keeping the 3rd keeps the chord clearly major or minor, while the added note sits a step away from one of its own notes, giving a soft, shimmering clash.",
    sources: ["vault:Research/glossary/add.md", "Open Music Theory, \"Chord Symbols\" — https://viva.pressbooks.pub/openmusictheory/chapter/chord-symbols/", "Open Music Theory, Glossary — https://viva.pressbooks.pub/openmusictheory/back-matter/glossary/"],
  },
  {
    id: "extension", term: "Extension",
    match: ["extension", "extensions"],
    plain: "A note stacked above the 7th of a seventh chord, carrying on in 3rds: the 9th, 11th and 13th. G9, for example, is G7 with the 9th added on top.",
    why: "Stacking 3rds past the 7th gives the 9th, 11th and 13th, which are the 2nd, 4th and 6th an octave up, adding colour without changing the root.",
    sources: ["vault:Research/glossary/extension.md", "Open Music Theory, \"Chord Symbols\" — https://viva.pressbooks.pub/openmusictheory/chapter/chord-symbols/", "Open Music Theory, \"Jazz Voicings\" — https://viva.pressbooks.pub/openmusictheory/chapter/jazz-voicings/"],
  },
  {
    id: "dominant_seventh", term: "Dominant 7th chord",
    match: ["dominant 7th", "dominant seventh", "dominant 7ths", "dominant sevenths"],
    plain: "A major triad plus a flat 7th (a whole step below the root an octave up), written simply as 7: G7, C7, D7. For open G7, play G and move the note on string 1 from fret 3 to fret 1.",
    why: "Its major 3rd and flat 7th form a tense, clashing interval that pulls toward the chord a 5th lower, which is why blues and rock lean on it.",
    sources: ["vault:Research/glossary/dominant_seventh.md", "musictheory.net, \"Seventh Chords\" — https://www.musictheory.net/lessons/45", "Open Music Theory, \"Blues Harmony\" — https://viva.pressbooks.pub/openmusictheory/chapter/blues-harmony/", "Open Music Theory, \"Chord Symbols\" — https://viva.pressbooks.pub/openmusictheory/chapter/chord-symbols/"],
  },
  {
    id: "open_chord", term: "Open chord / open string",
    match: ["open chord", "open chords", "open string", "open strings"],
    plain: "An open string is played with no finger on any fret. An open chord sits near the nut and lets some open strings ring: E, A, D, G, C, Em and Am are the common ones.",
    why: "Open strings ring longer and fuller than fretted ones, and open chords double the root and 5th across octaves, strengthening the consonant ring.",
    sources: ["vault:Research/glossary/open_chord.md", "JustinGuitar, \"CAGED System\" module (tier 4) — https://www.justinguitar.com/modules/caged-system", "JustinGuitar, \"The CAGED System G Shape\" (tier 4) — https://www.justinguitar.com/guitar-lessons/the-caged-system-g-shape-tb-036"],
  },
  {
    id: "barre", term: "Barre",
    match: ["barre", "barres", "barre chord", "barre chords"],
    plain: "One finger, usually the first, pressed flat across several strings at the same fret, with the other fingers making a shape in front of it. A barre chord can move to any fret to change its name.",
    why: "Each fret is a half step, so moving a barre shape up two frets raises the whole chord a whole step: one shape gives all twelve major chords.",
    sources: ["vault:Research/glossary/barre.md", "JustinGuitar, \"CAGED System\" module (tier 4) — https://www.justinguitar.com/modules/caged-system", "JustinGuitar, \"The CAGED System G Shape\" (tier 4) — https://www.justinguitar.com/guitar-lessons/the-caged-system-g-shape-tb-036"],
  },
  {
    id: "power_chord", term: "Power chord",
    match: ["power chord", "power chords"],
    plain: "Just two notes, the root and its 5th, on neighbouring low strings: first finger on the root, third finger two frets higher on the next string up. Written with a 5, as in A5. It has no 3rd, so it is neither major nor minor.",
    why: "The 5th is the most consonant interval after the octave, so the pair sounds solid and stays clear even with heavy distortion, where a full chord turns muddy.",
    sources: ["vault:Research/glossary/power_chord.md", "Open Music Theory, Intervals — https://viva.pressbooks.pub/openmusictheory/chapter/intervals/", "ArtistWorks (Keith Wyatt), Boogie Shuffle Blues Guitar — https://blog.artistworks.com/boogie-shuffle-blues-guitar-5-proven-skills-to-master-the-groove/"],
  },
  {
    id: "caged", term: "CAGED",
    match: ["caged", "e-shape", "a-shape", "c-shape", "g-shape", "d-shape"],
    plain: "A system linking the five open chord shapes C, A, G, E and D. Each can be moved up the neck as a barre shape, so any chord can be played in five places, one shape joining the next.",
    why: "The fretboard repeats every twelve frets, an octave, so the five shapes join end to end and cover the whole neck for any root.",
    sources: ["vault:Research/glossary/caged.md", "JustinGuitar, \"CAGED System\" module (tier 4) — https://www.justinguitar.com/modules/caged-system", "JustinGuitar, \"The CAGED System G Shape\" (tier 4) — https://www.justinguitar.com/guitar-lessons/the-caged-system-g-shape-tb-036"],
  },
  {
    id: "double_stop", term: "Double-stop",
    match: ["double-stop", "double-stops", "double stop", "double stops"],
    plain: "Two notes played together on two strings, usually neighbours (sometimes with one string skipped), picked or strummed. They are often taken from the chord being played, such as the top two strings of a barre shape.",
    why: "Two notes make one interval, the core of every chord; 3rds and 6ths sound sweet and consonant, which is why players reach for them most.",
    sources: ["vault:Research/glossary/double_stop.md", "Fender, \"Justus West Teaches Double Stops\" (tier 4) — https://www.youtube.com/watch?v=SRDuZ2AGRJM", "Open Music Theory, \"Intervals\" — https://viva.pressbooks.pub/openmusictheory/chapter/intervals/"],
  },
  {
    id: "slash_chord", term: "Slash chord",
    match: ["slash chord", "slash chords"],
    plain: "A chord written with a slash, as in G/B: play G, but with B as the lowest note. The letter after the slash says which note goes on the lowest string you play.",
    why: "Changing the lowest note shifts the chord's weight without changing its name; G/B is simply G in first inversion, with the 3rd on the bottom.",
    sources: ["vault:Research/glossary/slash_chord.md", "Open Music Theory, \"Chord Symbols\" — https://viva.pressbooks.pub/openmusictheory/chapter/chord-symbols/", "Open Music Theory, \"Inversion\" — https://viva.pressbooks.pub/openmusictheory/chapter/inversion/"],
  },
  {
    id: "progression", term: "Progression",
    match: ["progression", "progressions", "chord progression", "chord progressions"],
    plain: "A series of chords played in order, often looped, such as G, C, D, G. Most songs are built from a few progressions repeated.",
    why: "Chords that share notes or whose roots move by a 5th connect smoothly, and moving away from the home chord and back gives a sense of journey.",
    sources: ["vault:Research/glossary/progression.md", "Open Music Theory, \"Introduction to Harmony, Cadences, and Phrase Endings\" — https://viva.pressbooks.pub/openmusictheory/chapter/intro-to-harmony/", "Open Music Theory, \"Roman Numerals\" — https://viva.pressbooks.pub/openmusictheory/chapter/roman-numerals/"],
  },
  {
    id: "numeral", term: "Roman numerals (I, IV, V…)",
    match: ["numeral", "numerals", "roman numeral", "roman numerals"],
    plain: "Roman numerals count chords from the home note: I is the chord built on note 1, IV on note 4, V on note 5. Upper case means major and lower case means minor, as in ii, iii and vi.",
    why: "Counting by scale degree shows a progression's shape in any key: I-IV-V is G-C-D in G and A-D-E in A, because the major scale's step pattern never changes.",
    sources: ["vault:Research/glossary/numeral.md", "Open Music Theory, \"Roman Numerals\" — https://viva.pressbooks.pub/openmusictheory/chapter/roman-numerals/"],
  },
  {
    id: "harmony", term: "Harmony",
    match: ["harmony", "harmonies"],
    plain: "Notes sounding at the same time, and the way chords follow one another. Strumming chords under a sung tune is harmony.",
    why: "Notes whose frequencies line up in simple ratios, like an octave (2:1) or a 5th (3:2), share overtones and blend, which is why some combinations sound consonant.",
    sources: ["vault:Research/glossary/harmony.md", "Open Music Theory, \"Introduction to Harmony, Cadences, and Phrase Endings\" — https://viva.pressbooks.pub/openmusictheory/chapter/intro-to-harmony/", "HyperPhysics, \"Consonance and Dissonance\" — http://hyperphysics.phy-astr.gsu.edu/hbase/Music/mussca.html"],
  },
  {
    id: "melody", term: "Melody",
    match: ["melody", "melodies", "melodic"],
    plain: "A tune: single notes one after another, the part you would sing or hum. On guitar it is usually picked one note at a time, often on the higher strings.",
    why: "A melody moves mostly by half and whole steps through the scale, and it feels settled when it lands on a note of the chord underneath.",
    sources: ["vault:Research/glossary/melody.md", "Open Music Theory, \"Melody and Phrasing\" — https://viva.pressbooks.pub/openmusictheory/chapter/melody-and-phrasing/", "Open Music Theory, \"Texture\" — https://viva.pressbooks.pub/openmusictheory/chapter/texture/"],
  },
  {
    id: "resolve", term: "Resolve / resolution",
    match: ["resolve", "resolves", "resolved", "resolving", "resolution", "unresolved"],
    plain: "Moving from a restless sound to a settled one, usually by landing on the home chord or home note. You hear it as the end of a musical sentence.",
    why: "Clashing intervals sound unstable, and the ear wants them to move by a half step or whole step to consonant ones; that move is resolution.",
    sources: ["vault:Research/glossary/resolve.md", "Open Music Theory, \"Introduction to Harmony, Cadences, and Phrase Endings\" — https://viva.pressbooks.pub/openmusictheory/chapter/intro-to-harmony/", "Open Music Theory, \"Strengthening Endings with V7\" — https://viva.pressbooks.pub/openmusictheory/chapter/strengthening-endings-with-v7/"],
  },
  {
    id: "tension", term: "Tension",
    match: ["tension"],
    plain: "The restless, unfinished feeling of a chord or note that wants to move on, such as a V chord just before the home chord. Building and releasing tension keeps music moving forward.",
    why: "Dissonant intervals, like the clash between the 3rd and 7th of a dominant 7th chord, create tension; resolving them to consonant ones releases it.",
    sources: ["vault:Research/glossary/tension.md", "Open Music Theory, \"Introduction to Harmony, Cadences, and Phrase Endings\" — https://viva.pressbooks.pub/openmusictheory/chapter/intro-to-harmony/", "HyperPhysics, \"Consonance and Dissonance\" — http://hyperphysics.phy-astr.gsu.edu/hbase/Music/mussca.html"],
  },
  {
    id: "dominant", term: "Dominant (V)",
    match: ["dominant"],
    plain: "The chord built on the 5th note of the scale, labelled V: D in the key of G. It pulls strongly back to the home chord, I.",
    why: "V contains the note a half step below the home note (the 7th degree), which leans up into it; adding the flat 7th makes the pull even stronger.",
    sources: ["vault:Research/glossary/dominant.md", "Open Music Theory, \"Strengthening Endings with V7\" — https://viva.pressbooks.pub/openmusictheory/chapter/strengthening-endings-with-v7/", "Open Music Theory, \"Roman Numerals\" — https://viva.pressbooks.pub/openmusictheory/chapter/roman-numerals/"],
  },
  {
    id: "secondary_dominant", term: "Secondary dominant",
    match: ["secondary dominant", "secondary dominants", "v of v"],
    plain: "A major or dominant 7th chord that acts as the V of a chord other than home. In G, A7 is the V of D (written V/V), so it pulls toward D rather than G.",
    why: "It copies the pull of a V chord by adding a note from outside the key (often a sharp), so the target chord briefly sounds like a new home note.",
    sources: ["vault:Research/glossary/secondary_dominant.md", "Open Music Theory, \"Tonicization\" — https://viva.pressbooks.pub/openmusictheory/chapter/tonicization/", "Open Music Theory, \"Roman Numerals\" — https://viva.pressbooks.pub/openmusictheory/chapter/roman-numerals/"],
  },
  {
    id: "borrowed", term: "Borrowed chord",
    match: ["borrowed chord", "borrowed chords", "borrowing", "borrow", "borrows"],
    plain: "A chord taken from the parallel key, the minor key with the same home note (or the major, if you are in minor). In G major, C minor (iv) and F major (bVII) are borrowed from G minor.",
    why: "Swapping a note of the major scale for its flat version, such as the 3rd, 6th or 7th, darkens the chord while the home note stays the same.",
    sources: ["vault:Research/glossary/borrowed.md", "Open Music Theory, \"Modal Mixture\" — https://viva.pressbooks.pub/openmusictheory/chapter/modal-mixture/", "Open Music Theory, \"Roman Numerals\" — https://viva.pressbooks.pub/openmusictheory/chapter/roman-numerals/"],
  },
  {
    id: "colour_note", term: "Colour note",
    match: ["colour note", "colour notes", "color note", "color notes"],
    plain: "A note that gives a scale or chord its own flavour, usually one fret above or below a note of the major scale: b3, b6, b7 or #4. In G, b7 is F, one fret below F#.",
    why: "Each mode or borrowed chord differs from the major scale by one or two notes, and those half-step changes are what the ear hears as colour.",
    sources: ["vault:Research/glossary/colour_note.md", "Open Music Theory, \"Chord-Scale Theory\" — https://viva.pressbooks.pub/openmusictheory/chapter/chord-scale-theory/", "Open Music Theory, \"Modal Mixture\" — https://viva.pressbooks.pub/openmusictheory/chapter/modal-mixture/"],
  },
  {
    id: "voice_leading", term: "Voice leading",
    match: ["voice leading", "voice-leading"],
    plain: "Moving each note of one chord to the nearest note of the next, so the change sounds smooth. On guitar it often means choosing inversions so your fingers barely move.",
    why: "Notes moving by a half step or whole step are easy for the ear to follow, so small moves join chords smoothly and shared notes can simply stay put.",
    sources: ["vault:Research/glossary/voice_leading.md", "Open Music Theory, \"Blues Harmony\" — https://viva.pressbooks.pub/openmusictheory/chapter/blues-harmony/", "Open Music Theory, \"Jazz Voicings\" — https://viva.pressbooks.pub/openmusictheory/chapter/jazz-voicings/", "Open Music Theory, \"Inversion\" — https://viva.pressbooks.pub/openmusictheory/chapter/inversion/"],
  },
  {
    id: "harmonic_rhythm", term: "Harmonic rhythm",
    match: ["harmonic rhythm"],
    plain: "How often the chords change: every four counts, twice as often, or only now and then. It is separate from how fast you strum.",
    why: "Each chord change is a new event the ear tracks against the steady pulse, so faster changes raise energy and slower ones feel calmer.",
    sources: ["vault:Research/glossary/harmonic_rhythm.md", "Open Music Theory, Glossary — https://viva.pressbooks.pub/openmusictheory/back-matter/glossary/", "Open Music Theory, \"Introduction to Harmony, Cadences, and Phrase Endings\" — https://viva.pressbooks.pub/openmusictheory/chapter/intro-to-harmony/"],
  },
  {
    id: "modulation", term: "Modulation (key change)",
    match: ["modulation", "modulate", "modulates", "key change", "key changes"],
    plain: "Changing key partway through a song, so a new home note takes over. A common pop move shifts everything up one or two frets for the last section.",
    why: "A key is a scale built on a home note; moving to a new home changes which notes sound stable and which sound restless, so the music feels lifted.",
    sources: ["vault:Research/glossary/modulation.md", "Shaffer et al., Music Theory for the 21st-Century Classroom, \"Modulations with Diatonic Pivot Chords\" — https://musictheory.pugetsound.edu/mt21c/ModulationsWithDiatonicPivotChords.html", "Open Music Theory, Glossary — https://viva.pressbooks.pub/openmusictheory/back-matter/glossary/"],
  },
  {
    id: "pivot_chord", term: "Pivot chord",
    match: ["pivot chord", "pivot chords", "pivot-chord"],
    plain: "A chord that belongs to both the old key and the new one, used as the hinge for a key change. The keys of G and D share G, D, Em and Bm.",
    why: "Because the pivot fits both keys, the ear accepts it in the old key, then hears it pointing to the new home, so the change sounds smooth rather than sudden.",
    sources: ["vault:Research/glossary/pivot_chord.md", "Shaffer et al., Music Theory for the 21st-Century Classroom, \"Modulations with Diatonic Pivot Chords\" — https://musictheory.pugetsound.edu/mt21c/ModulationsWithDiatonicPivotChords.html"],
  },
  {
    id: "beat", term: "Beat",
    match: ["beat", "beats"],
    plain: "The steady pulse you tap your foot to. Count it out loud as 1 2 3 4: each number is one beat, and every strum or picked note is timed against it.",
    why: "Pulse is the floor of all rhythm: every longer or shorter sound is measured in beats, the way pitch is measured in frets.",
    sources: ["vault:Research/glossary/beat.md", "Open Music Theory, \"Simple Meter and Time Signatures\" — https://viva.pressbooks.pub/openmusictheory/chapter/meter/", "musictheory.net, \"Simple and Compound Meter\" — https://www.musictheory.net/lessons/15"],
  },
  {
    id: "bar", term: "Bar",
    match: ["bar", "bars"],
    plain: "A group of beats, usually four, counted 1 2 3 4 and then back to 1. Also called a measure. \"One chord per bar\" means change chord each time you get back to 1.",
    why: "Bars give the pulse a shape: beat 1 feels strongest, so chord changes and new ideas usually land there, and songs are built in 4-bar and 8-bar blocks.",
    sources: ["vault:Research/glossary/bar.md", "musictheory.net, \"Measures and Time Signature\" — https://www.musictheory.net/lessons/12", "Open Music Theory, \"Simple Meter and Time Signatures\" — https://viva.pressbooks.pub/openmusictheory/chapter/meter/"],
  },
  {
    id: "bpm", term: "Tempo (bpm)",
    match: ["bpm", "tempo"],
    plain: "Tempo is how fast the beats go, measured in bpm (beats per minute): 60 bpm is one beat each second. The app raises the tempo by 5 bpm after each clean pass and drops it back 5 after two misses.",
    why: "Tempo changes how fast the pulse ticks, not where things land in the bar, so a pattern learned slowly and cleanly stays correct as you speed it up.",
    sources: ["vault:Research/glossary/bpm.md", "musictheory.net, Tempo Tapper (beats per minute) — https://www.musictheory.net/tools", "Open Music Theory, \"Simple Meter and Time Signatures\" — https://viva.pressbooks.pub/openmusictheory/chapter/meter/"],
  },
  {
    id: "downbeat", term: "Downbeat",
    match: ["downbeat", "downbeats"],
    plain: "Beat 1 of a bar: the first count, where you land each time you count 1 2 3 4 and start again. More loosely, any beat you count with a number rather than an \"&\".",
    why: "The downbeat is the strongest point of the bar, so landing a chord or root there sounds settled, and moving away from it creates pull.",
    sources: ["vault:Research/glossary/downbeat.md", "Open Music Theory, \"Simple Meter and Time Signatures\" — https://viva.pressbooks.pub/openmusictheory/chapter/meter/", "Open Music Theory, Glossary — https://viva.pressbooks.pub/openmusictheory/back-matter/glossary/"],
  },
  {
    id: "subdivision", term: "Subdivision (8ths, 16ths)",
    match: ["subdivision", "subdivisions", "8ths", "16ths", "8th", "16th", "eighth", "eighths", "sixteenth", "sixteenths"],
    plain: "Splitting each beat into smaller equal parts. Two per beat are 8ths, counted \"1 & 2 & 3 & 4 &\". Four per beat are 16ths, counted \"1 e & a 2 e & a\". Your strumming hand moves down on the numbers and up on the \"&\".",
    why: "Subdivision is the ruler inside the beat: counting the small parts keeps every strum evenly spaced, and it is where all rhythm patterns are placed.",
    sources: ["vault:Research/glossary/subdivision.md", "Open Music Theory, \"Simple Meter and Time Signatures\" — https://viva.pressbooks.pub/openmusictheory/chapter/meter/", "musictheory.net, \"Simple and Compound Meter\" — https://www.musictheory.net/lessons/15"],
  },
  {
    id: "offbeat", term: "Offbeat / the \"and\"",
    match: ["offbeat", "offbeats", "off-beat"],
    plain: "The points halfway between the beats: the \"&\" when you count \"1 & 2 & 3 & 4 &\". On guitar the offbeats usually fall on the up-strums.",
    why: "Sounds on the offbeat lean against the pulse instead of sitting on it, which creates lift and push; reggae and ska guitar live there.",
    sources: ["vault:Research/glossary/offbeat.md", "Open Music Theory, \"Other Rhythmic Essentials\" (syncopation, backbeat) — https://viva.pressbooks.pub/openmusictheory/chapter/other-rhythmic-essentials/", "Open Music Theory, \"Simple Meter and Time Signatures\" — https://viva.pressbooks.pub/openmusictheory/chapter/meter/"],
  },
  {
    id: "triplet", term: "Triplet",
    match: ["triplet", "triplets"],
    plain: "Three equal parts squeezed into one beat instead of two, counted \"1 trip-let 2 trip-let\". It gives a rolling, three-step feel compared with plain 8ths.",
    why: "A beat can divide into two or three; three-way division drives the long-short blues feel and 6/8 time, so learn to hear both kinds of subdivision.",
    sources: ["vault:Research/glossary/triplet.md", "Open Music Theory, \"Compound Meter and Time Signatures\" — https://viva.pressbooks.pub/openmusictheory/chapter/compound-meters-and-time-signatures/", "musictheory.net, \"Simple and Compound Meter\" — https://www.musictheory.net/lessons/15"],
  },
  {
    id: "shuffle", term: "Shuffle / swing",
    match: ["shuffle", "shuffles", "swing", "swings", "swung"],
    plain: "A feel where each pair of 8ths is played long-short instead of even, using the first and last parts of a triplet: \"1-a-lah, 2-a-lah\". Blues and jazz are usually played this way.",
    why: "Swing keeps the beat and bar exactly the same but changes the subdivision from two even parts to a long-short triplet split, which is why it feels loping.",
    sources: ["vault:Research/glossary/shuffle.md", "Open Music Theory, \"Swing Rhythms\" — https://viva.pressbooks.pub/openmusictheory/chapter/swing-rhythms/", "Open Music Theory, \"Compound Meter and Time Signatures\" — https://viva.pressbooks.pub/openmusictheory/chapter/compound-meters-and-time-signatures/"],
  },
  {
    id: "syncopation", term: "Syncopation",
    match: ["syncopation", "syncopated"],
    plain: "Putting strong sounds where the listener does not expect them: on an offbeat, or just before a beat, instead of on the beat itself.",
    why: "Our ears expect weight on the strong beats; syncopation breaks that pattern on purpose, creating a small surprise that makes rhythm feel alive.",
    sources: ["vault:Research/glossary/syncopation.md", "Open Music Theory, \"Other Rhythmic Essentials\" (syncopation, backbeat) — https://viva.pressbooks.pub/openmusictheory/chapter/other-rhythmic-essentials/", "Open Music Theory, Glossary — https://viva.pressbooks.pub/openmusictheory/back-matter/glossary/"],
  },
  {
    id: "anticipation", term: "Anticipation",
    match: ["anticipation", "anticipated", "anticipations", "anticipate"],
    plain: "Playing a chord change a little early, usually on the \"&\" of beat 4, so it arrives before beat 1 of the next bar instead of on it.",
    why: "It is a common kind of syncopation: the change lands on an offbeat, so the downbeat it replaces feels pushed forward.",
    sources: ["vault:Research/glossary/anticipation.md", "Open Music Theory, \"Other Rhythmic Essentials\" (syncopation, backbeat) — https://viva.pressbooks.pub/openmusictheory/chapter/other-rhythmic-essentials/", "Open Music Theory, Glossary — https://viva.pressbooks.pub/openmusictheory/back-matter/glossary/"],
  },
  {
    id: "backbeat", term: "Backbeat",
    match: ["backbeat", "backbeats"],
    plain: "Stress on beats 2 and 4 of a four-beat bar, where the drummer usually hits the snare. On guitar it is often a muted, percussive strum or a harder strum on 2 and 4.",
    why: "Classical music tends to stress beats 1 and 3; stressing 2 and 4 is a built-in syncopation, and it is the engine of most rock, pop and soul.",
    sources: ["vault:Research/glossary/backbeat.md", "Open Music Theory, \"Other Rhythmic Essentials\" (syncopation, backbeat) — https://viva.pressbooks.pub/openmusictheory/chapter/other-rhythmic-essentials/", "Open Music Theory, \"Drumbeats\" — https://viva.pressbooks.pub/openmusictheory/chapter/drumbeats/"],
  },
  {
    id: "accent", term: "Accent",
    match: ["accent", "accents", "accented"],
    plain: "Making one sound louder or sharper than the ones around it, such as a harder strum on certain counts, so it stands out.",
    why: "Accents decide which parts of the subdivision you hear as important; moving them is how a fixed strumming motion becomes a recognisable rhythm.",
    sources: ["vault:Research/glossary/accent.md", "Open Music Theory, \"Other Rhythmic Essentials\" (syncopation, backbeat) — https://viva.pressbooks.pub/openmusictheory/chapter/other-rhythmic-essentials/", "Open Music Theory, \"Simple Meter and Time Signatures\" — https://viva.pressbooks.pub/openmusictheory/chapter/meter/"],
  },
  {
    id: "groove", term: "Groove",
    match: ["groove", "grooves"],
    plain: "The overall rhythmic feel of a part: the tempo, which beats are accented, and whether it is straight or swung, settling into a pattern that makes people want to move.",
    why: "Groove is beat, subdivision and accent locked together and repeated, steady enough to predict and varied enough to be interesting.",
    sources: ["vault:Research/glossary/groove.md", "Open Music Theory, \"Drumbeats\" — https://viva.pressbooks.pub/openmusictheory/chapter/drumbeats/", "Open Music Theory, \"Swing Rhythms\" — https://viva.pressbooks.pub/openmusictheory/chapter/swing-rhythms/"],
  },
  {
    id: "vamp", term: "Vamp",
    match: ["one-chord vamp", "vamp", "vamps"],
    plain: "A short chord pattern repeated over and over, often a single chord held for many bars. Funk lives on one-chord vamps: the band sits on one chord and the groove does the work.",
    why: "With the harmony standing still, your ear moves to rhythm and tone, so small changes in timing and muting become the music.",
    sources: ["vault:Research/glossary/vamp.md", "Wikipedia, \"Vamp (music)\" (tier 5) — https://en.wikipedia.org/wiki/Vamp_(music)", "Premier Guitar, \"One-Chord Vamps and the Truth\" (tier 4) — https://www.premierguitar.com/lessons/scales/minor-pentatonic-scale"],
  },
  {
    id: "dynamics", term: "Dynamics",
    match: ["dynamics", "dynamic"],
    plain: "How loud or soft the music is, and how that changes over time. On guitar: how hard you strum or pick, and how many strings ring.",
    why: "Volume changes shape tension and release just as harmony does; a quiet section makes the loud one feel bigger.",
    sources: ["vault:Research/glossary/dynamics.md", "Open Music Theory, Glossary — https://viva.pressbooks.pub/openmusictheory/back-matter/glossary/", "Open Music Theory, \"Introduction to Form in Popular Music\" — https://viva.pressbooks.pub/openmusictheory/chapter/intro-to-form-in-popular-music/"],
  },
  {
    id: "stop_time", term: "Stop-time",
    match: ["stop-time", "stop time"],
    plain: "The band plays one short, sharp hit, usually on beat 1, then goes silent for the rest of the bar (or longer) while the singer or soloist carries on, before everyone comes back in.",
    why: "The pulse keeps going in everyone's head during the silence; stop-time shows how strong the beat is by taking the sound away from it.",
    sources: ["vault:Research/glossary/stop_time.md", "Open Music Theory, \"Drumbeats\" — https://viva.pressbooks.pub/openmusictheory/chapter/drumbeats/", "Open Music Theory, Glossary — https://viva.pressbooks.pub/openmusictheory/back-matter/glossary/"],
  },
  {
    id: "twelve_bar", term: "12-bar blues",
    match: ["12-bar blues", "12-bar", "twelve-bar blues", "twelve-bar"],
    plain: "The classic blues layout over 12 bars: four of I, two of IV, two of I, then V, IV, I, V. Usually played as dominant 7th chords with a long-short, swinging strum; variants move to IV in bar 2 or shorten it to 8 bars.",
    why: "I, IV and V are the home chord and its two closest neighbours, a 5th below and a 5th above, so the pattern feels like leaving home and returning.",
    sources: ["vault:Research/glossary/twelve_bar.md", "Open Music Theory, \"Blues Harmony\" — https://viva.pressbooks.pub/openmusictheory/chapter/blues-harmony/", "Wikipedia, \"Twelve-bar blues\" (tier 5, variants only) — https://en.wikipedia.org/wiki/Twelve-bar_blues"],
  },
  {
    id: "quick_change", term: "Quick change",
    match: ["quick change", "quick-change", "quick to four"],
    plain: "A 12-bar blues that moves to the IV chord in bar 2 and back to I in bar 3, instead of staying on I for the first four bars. In G: G7, C7, G7, G7.",
    why: "In G, the IV chord C7 contains B flat, the flat 3rd of G and a blue note, so the quick change brings that bluesy clash in early.",
    sources: ["vault:Research/glossary/quick_change.md", "Open Music Theory, \"Blues Harmony\" — https://viva.pressbooks.pub/openmusictheory/chapter/blues-harmony/", "Wikipedia, \"Twelve-bar blues\" (tier 5, variants only) — https://en.wikipedia.org/wiki/Twelve-bar_blues"],
  },
  {
    id: "turnaround", term: "Turnaround",
    match: ["turnaround", "turnarounds"],
    plain: "The last two bars of a 12-bar blues, which head back to V so the form can start again. On guitar it is often a short lick walking down the higher strings onto V7.",
    why: "Ending on V leaves the tension unresolved, so the ear expects the home chord next and the pattern rolls naturally into its next pass.",
    sources: ["vault:Research/glossary/turnaround.md", "Open Music Theory, \"Blues Harmony\" — https://viva.pressbooks.pub/openmusictheory/chapter/blues-harmony/", "Open Music Theory, Glossary — https://viva.pressbooks.pub/openmusictheory/back-matter/glossary/"],
  },
  {
    id: "palm_mute", term: "Palm muting",
    match: ["palm muting", "palm mute", "palm-muted", "palm muted", "palm mutes"],
    plain: "Resting the edge of your picking hand lightly on the strings right next to the bridge while you play, so they give a short, chunky thud instead of ringing.",
    why: "Muting cuts the ringing so each strum becomes short, which lets accents and rests stand out clearly against the beat.",
    sources: ["vault:Research/glossary/palm_mute.md", "JustinGuitar, \"Palm Muting\", Module 12 (tier 4) — https://community.justinguitar.com/t/palm-muting/2597", "JustinGuitar, \"Muting Strings Deliberately\" (tier 4) — https://www.justinguitar.com/guitar-lessons/muting-strings-deliberately-b2-804"],
  },
  {
    id: "boogie", term: "Boogie (5–6 riff)",
    match: ["boogie", "boogies", "root-5/root-6"],
    plain: "A rolling two-note riff on the low strings: a power chord (root + 5th), then the little finger reaches two frets further to make root + 6th, back and forth on every beat with a shuffle feel. Guitarists took it from the left hand of boogie-woogie piano.",
    why: "The root never moves, so the low end stays anchored, while the 5th-to-6th rocking adds motion; swung, it drives a 12-bar blues like a train.",
    sources: ["vault:Research/glossary/boogie.md", "ArtistWorks (Keith Wyatt), Boogie Shuffle Blues Guitar — https://blog.artistworks.com/boogie-shuffle-blues-guitar-5-proven-skills-to-master-the-groove/"],
  },
  {
    id: "chuck", term: "Chuck",
    match: ["chuck", "chucks"],
    plain: "A percussive strum where the fretting hand relaxes just enough to stop the strings ringing, so you hear a short \"chk\" instead of the chord. Shown as × in strumming patterns.",
    why: "A chuck turns the guitar into a drum: placed on beats 2 and 4 it plays the backbeat, while the other strums carry the chord.",
    sources: ["vault:Research/glossary/chuck.md", "JustinGuitar, \"Muting Strings Deliberately\" (tier 4) — https://www.justinguitar.com/guitar-lessons/muting-strings-deliberately-b2-804", "JustinGuitar, \"Guitar Strumming Tips\" (tier 4) — https://www.justinguitar.com/guitar-lessons/guitar-strumming-tips-b1-502"],
  },
  {
    id: "ghost_strum", term: "Ghost strum",
    match: ["ghost strum", "ghost strums", "ghost", "ghosts"],
    plain: "A strum where your hand keeps moving down and up in time but barely touches the strings, or misses them, so it is nearly silent.",
    why: "Ghost strums keep the hand marking every subdivision, so the strums you do hear land exactly in time.",
    sources: ["vault:Research/glossary/ghost_strum.md", "JustinGuitar, \"Guitar Strumming Tips\" (tier 4) — https://www.justinguitar.com/guitar-lessons/guitar-strumming-tips-b1-502", "JustinGuitar, \"Muting Strings Deliberately\" (tier 4) — https://www.justinguitar.com/guitar-lessons/muting-strings-deliberately-b2-804"],
  },
  {
    id: "hammer_on", term: "Hammer-on",
    match: ["hammer-on", "hammer-ons", "hammer on", "hammered"],
    plain: "Pick a note, then bring another finger down hard onto a higher fret of the same string so a second note sounds without picking again.",
    why: "The string is already vibrating; shortening it with a new fret raises the pitch, which is how two notes come from one pick stroke.",
    sources: ["vault:Research/glossary/hammer_on.md", "JustinGuitar, \"Beginner Hammer-Ons\" (tier 4) — https://www.justinguitar.com/guitar-lessons/beginner-hammer-ons-bg-1008"],
  },
  {
    id: "pull_off", term: "Pull-off",
    match: ["pull-off", "pull-offs", "pull off", "pulled off"],
    plain: "The reverse of a hammer-on: with two fingers on the same string, pick the higher note, then flick the top finger off sideways so the lower note sounds without picking again.",
    why: "Removing a finger lengthens the vibrating string, so the pitch drops; the flick re-plucks the string to keep it sounding.",
    sources: ["vault:Research/glossary/pull_off.md", "JustinGuitar, \"Legato 2: Flick-Offs\" (tier 4) — https://www.justinguitar.com/guitar-lessons/legato-2-flick-offs-lp-002", "JustinGuitar, \"Beginner Hammer-Ons\" (tier 4) — https://www.justinguitar.com/guitar-lessons/beginner-hammer-ons-bg-1008"],
  },
  {
    id: "slide", term: "Slide",
    match: ["slide", "slides", "sliding", "slid"],
    plain: "Play a note, then keep pressing while you move the same finger along the string to another fret, so the sound glides to the new note without picking again.",
    why: "Moving the finger changes the length of string that vibrates, so the pitch glides through every half step between the two frets.",
    sources: ["vault:Research/glossary/slide.md", "JustinGuitar, \"Guitar Strumming Tips\" (tier 4) — https://www.justinguitar.com/guitar-lessons/guitar-strumming-tips-b1-502", "JustinGuitar, \"Beginner Hammer-Ons\" (tier 4) — https://www.justinguitar.com/guitar-lessons/beginner-hammer-ons-bg-1008"],
  },
  {
    id: "pima", term: "p-i-m-a",
    match: ["p-i-m-a", "pima", "p-i-m"],
    plain: "Letters for the picking-hand fingers, from their Spanish names: p = pulgar (thumb), i = indice (index), m = medio (middle), a = anular (ring). Usually the thumb plays the low strings and i, m, a one higher string each.",
    why: "Giving each finger its own string lets you play the notes of a chord separately and at the same time, like a small band in one hand.",
    sources: ["vault:Research/glossary/pima.md", "Fender, \"What is PIMA?\" (tier 4) — https://www.fender.com/articles/techniques/what-is-pima", "Richter Guitar, \"Finger Names for Classical Guitar\" (tier 4) — https://richterguitar.com/what-are-the-classical-guitar-finger-names/"],
  },
  {
    id: "pinch", term: "Pinch",
    match: ["pinch", "pinches", "pinched"],
    plain: "Plucking a low string with the thumb and a higher string with a finger at the same moment, as if pinching the strings together.",
    why: "A pinch sounds a low and a high note together, giving the root underneath and the melody on top in one motion.",
    sources: ["vault:Research/glossary/pinch.md", "Richter Guitar, \"Finger Names for Classical Guitar\" (tier 4) — https://richterguitar.com/what-are-the-classical-guitar-finger-names/", "JustinGuitar, \"Basic Travis Picking\" FO-108 (tier 4) — https://community.justinguitar.com/t/basic-travis-picking/2155"],
  },
  {
    id: "arpeggio", term: "Arpeggio",
    match: ["arpeggio", "arpeggios", "arpeggiated", "arpeggiate"],
    plain: "The notes of a chord played one after another instead of all at once, for example picking the strings of a chord shape one at a time.",
    why: "An arpeggio spells the chord out (root, 3rd, 5th) in time, so you hear each note and the harmony at once.",
    sources: ["vault:Research/glossary/arpeggio.md", "Open Music Theory, Glossary — https://viva.pressbooks.pub/openmusictheory/back-matter/glossary/", "Open Music Theory, \"Triads\" (arpeggiation) — https://viva.pressbooks.pub/openmusictheory/chapter/triads/"],
  },
  {
    id: "alternate_bass", term: "Alternate bass / alternating thumb",
    match: ["alternate bass", "alternating bass", "alternating thumb"],
    plain: "The thumb switches back and forth between two low strings on the beats, usually the root and another note of the chord, while the fingers pick higher strings in between.",
    why: "Alternating root and 5th down low marks every beat, so a single guitar covers both the pulse and the harmony.",
    sources: ["vault:Research/glossary/alternate_bass.md", "JustinGuitar, \"Basic Travis Picking\" FO-108 (tier 4) — https://community.justinguitar.com/t/basic-travis-picking/2155", "Fender, \"What is PIMA?\" (tier 4) — https://www.fender.com/articles/techniques/what-is-pima"],
  },
  {
    id: "travis", term: "Travis picking",
    match: ["travis", "travis picking", "travis-picking", "travis pattern"],
    plain: "A fingerstyle pattern named after Merle Travis: the thumb alternates between two low strings on every beat while the fingers pick higher strings on the \"&\" between them.",
    why: "The steady thumb is the pulse and the fingers play the offbeats, so the pattern is a built-in syncopation.",
    sources: ["vault:Research/glossary/travis.md", "JustinGuitar, \"Basic Travis Picking\" FO-108 (tier 4) — https://community.justinguitar.com/t/basic-travis-picking/2155"],
  },
  {
    id: "bass_treble", term: "Bass and treble",
    match: ["bass", "treble", "bass note", "bass notes"],
    plain: "Bass means the low notes, on the thick strings (6, 5 and 4); treble means the high notes, on the thin strings (3, 2 and 1).",
    why: "The lowest note decides how a chord sounds most strongly, so the bass usually plays the root while the treble carries the melody and colour.",
    sources: ["vault:Research/glossary/bass_treble.md", "Open Music Theory, \"Core Principles of Orchestration\" (register) — https://viva.pressbooks.pub/openmusictheory/chapter/core-principles-of-orchestration/", "Open Music Theory, Glossary — https://viva.pressbooks.pub/openmusictheory/back-matter/glossary/"],
  },
  {
    id: "verse", term: "Verse",
    match: ["verse", "verses"],
    plain: "The part of a song that tells the story: the music repeats each time but the words change. Verses usually lead into the main section that repeats with the same words.",
    why: "Verses usually sit lower and calmer in energy so the next section can lift above them; the contrast is what makes the song feel like it goes somewhere.",
    sources: ["vault:Research/glossary/verse.md", "Open Music Theory, \"Verse-Chorus Form\" — https://viva.pressbooks.pub/openmusictheory/chapter/verse-chorus-form/", "Open Music Theory, \"Introduction to Form in Popular Music\" — https://viva.pressbooks.pub/openmusictheory/chapter/intro-to-form-in-popular-music/"],
  },
  {
    id: "chorus", term: "Chorus",
    match: ["chorus", "choruses"],
    plain: "The part of a song that comes back with the same words each time, usually carrying the title and the most memorable melody. It is often the loudest, highest part.",
    why: "The chorus releases the tension built in the verse, often by landing on the home chord and raising the energy.",
    sources: ["vault:Research/glossary/chorus.md", "Open Music Theory, \"Verse-Chorus Form\" — https://viva.pressbooks.pub/openmusictheory/chapter/verse-chorus-form/", "Open Music Theory, \"Introduction to Form in Popular Music\" — https://viva.pressbooks.pub/openmusictheory/chapter/intro-to-form-in-popular-music/"],
  },
  {
    id: "pre_chorus", term: "Pre-chorus",
    match: ["pre-chorus", "pre-choruses", "prechorus"],
    plain: "A short section between the verse and the chorus that builds anticipation, often with new chords, rising energy, and stopping just before the chorus arrives.",
    why: "The pre-chorus builds tension, often ending on the dominant or an unresolved chord, so the chorus feels like a release when it lands.",
    sources: ["vault:Research/glossary/pre_chorus.md", "Open Music Theory, \"Verse-Chorus Form\" — https://viva.pressbooks.pub/openmusictheory/chapter/verse-chorus-form/", "Open Music Theory, \"Introduction to Form in Popular Music\" — https://viva.pressbooks.pub/openmusictheory/chapter/intro-to-form-in-popular-music/"],
  },
  {
    id: "phrase", term: "Phrase",
    match: ["phrase", "phrases", "phrasing"],
    plain: "A short musical idea with a beginning, middle and end, like a sentence in speech, usually 2 or 4 bars long and often ending with a breath or pause.",
    why: "Phrases end on a goal, often a resolution to the home note or chord, which is why music feels like it is speaking in sentences.",
    sources: ["vault:Research/glossary/phrase.md", "Open Music Theory, \"Melody and Phrasing\" — https://viva.pressbooks.pub/openmusictheory/chapter/melody-and-phrasing/", "Open Music Theory, Glossary — https://viva.pressbooks.pub/openmusictheory/back-matter/glossary/"],
  },
  {
    id: "register", term: "Register",
    match: ["register", "registers"],
    plain: "How high or low a passage sits overall: the same melody can be played in a low, middle or high register, for example lower on the neck or an octave up.",
    why: "Moving to a higher register raises energy and brightness without changing the notes, which is why choruses often sit higher than verses.",
    sources: ["vault:Research/glossary/register.md", "Open Music Theory, \"Core Principles of Orchestration\" (register) — https://viva.pressbooks.pub/openmusictheory/chapter/core-principles-of-orchestration/", "Open Music Theory, Glossary — https://viva.pressbooks.pub/openmusictheory/back-matter/glossary/"],
  },
  {
    id: "prosody", term: "Prosody",
    match: ["prosody"],
    plain: "When the music fits what the words mean: the melody, rhythm, chords and phrasing all support the feeling of the lyric. Stressed syllables fall on strong beats.",
    why: "Strong beats, rising melody, and resolution all carry feeling on their own; prosody lines those feelings up with the meaning of the words.",
    sources: ["vault:Research/glossary/prosody.md", "Pat Pattison, \"Prosody in Music and Songwriting\", Berklee Online — https://online.berklee.edu/takenote/prosody-in-music-and-songwriting/"],
  },
];

const escape = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

/** Glossary entries whose words appear in `texts`, longest phrase first, de-duplicated, in order of first appearance. */
export function termsIn(texts: string[], glossary: GlossaryEntry[] = GLOSSARY): GlossaryEntry[] {
  const byMatch = new Map(glossary.flatMap(g => g.match.map(m => [m, g] as const)));
  if (byMatch.size === 0) return [];
  const words = [...byMatch.keys()].sort((a, b) => b.length - a.length).map(escape).join('|');
  const re = new RegExp(`(?<![\\w'-])(${words})(?![\\w'-])`, 'gi');
  const found: GlossaryEntry[] = [];
  for (const text of texts) {
    for (const m of text.replace(/\{[^}]*\}/g, ' ').matchAll(re)) {
      const g = byMatch.get(m[1].toLowerCase());
      if (g && !found.includes(g)) found.push(g);
    }
  }
  return found;
}
