/**
 * Writes supabase/seed.sql from supabase/seed/curriculum.ts (supabase db reset runs it).
 *   node scripts/gen-seed-sql.ts
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Skill } from '../supabase/functions/_shared/engine/types.ts';
import { SKILLS } from '../supabase/seed/curriculum.ts';
import { REPO_ROOT, isMain } from './vault/lib.ts';

const lit = (v: string | number | null) => (v === null ? 'null' : typeof v === 'number' ? String(v) : `'${v.replace(/'/g, "''")}'`);
const arr = (v: string[] | null) => (v ? `array[${v.map(lit).join(',')}]::text[]` : 'null');

/** Idempotent upsert SQL for the skills table; theory rows first so theory_topic_id FKs resolve. */
export function skillsToSql(skills: Skill[]): string {
  const ordered = [...skills].sort((a, b) => Number(b.track === 'theory') - Number(a.track === 'theory'));
  const rows = ordered.map(s => `  (${[lit(s.id), lit(s.track), s.level, lit(s.name), lit(s.description), lit(s.pass_metric),
    lit(s.default_target), arr(s.allowed_keys), lit(s.theory_topic_id), arr(s.styles)].join(', ')})`);
  return `-- Generated by scripts/gen-seed-sql.ts from supabase/seed/curriculum.ts. Do not edit by hand.
insert into public.skills (id, track, level, name, description, pass_metric, default_target, allowed_keys, theory_topic_id, styles) values
${rows.join(',\n')}
on conflict (id) do update set track = excluded.track, level = excluded.level, name = excluded.name,
  description = excluded.description, pass_metric = excluded.pass_metric, default_target = excluded.default_target,
  allowed_keys = excluded.allowed_keys, theory_topic_id = excluded.theory_topic_id, styles = excluded.styles;
`;
}

if (isMain(import.meta.url)) {
  const out = join(REPO_ROOT, 'supabase', 'seed.sql');
  writeFileSync(out, skillsToSql(SKILLS));
  console.log(`${SKILLS.length} skills → ${out}`);
}
